"""
A predefined dictionary of technical and soft skills, categorized.
Used for matching and extraction.
"""

from app.models.skill import SkillCategory

SKILLS_DICTIONARY = {
    # Programming Languages
    "python": SkillCategory.PROGRAMMING_LANGUAGE,
    "javascript": SkillCategory.PROGRAMMING_LANGUAGE,
    "typescript": SkillCategory.PROGRAMMING_LANGUAGE,
    "java": SkillCategory.PROGRAMMING_LANGUAGE,
    "c++": SkillCategory.PROGRAMMING_LANGUAGE,
    "cpp": SkillCategory.PROGRAMMING_LANGUAGE,
    "c#": SkillCategory.PROGRAMMING_LANGUAGE,
    "csharp": SkillCategory.PROGRAMMING_LANGUAGE,
    "c": SkillCategory.PROGRAMMING_LANGUAGE,
    "ruby": SkillCategory.PROGRAMMING_LANGUAGE,
    "go": SkillCategory.PROGRAMMING_LANGUAGE,
    "golang": SkillCategory.PROGRAMMING_LANGUAGE,
    "rust": SkillCategory.PROGRAMMING_LANGUAGE,
    "php": SkillCategory.PROGRAMMING_LANGUAGE,
    "swift": SkillCategory.PROGRAMMING_LANGUAGE,
    "kotlin": SkillCategory.PROGRAMMING_LANGUAGE,
    "scala": SkillCategory.PROGRAMMING_LANGUAGE,
    "r": SkillCategory.PROGRAMMING_LANGUAGE,
    "matlab": SkillCategory.PROGRAMMING_LANGUAGE,
    "html": SkillCategory.PROGRAMMING_LANGUAGE,
    "css": SkillCategory.PROGRAMMING_LANGUAGE,
    "sql": SkillCategory.PROGRAMMING_LANGUAGE,
    "bash": SkillCategory.PROGRAMMING_LANGUAGE,
    "dart": SkillCategory.PROGRAMMING_LANGUAGE,
    "objective-c": SkillCategory.PROGRAMMING_LANGUAGE,
    "perl": SkillCategory.PROGRAMMING_LANGUAGE,

    # Frameworks
    "react": SkillCategory.FRAMEWORK,
    "angular": SkillCategory.FRAMEWORK,
    "vue": SkillCategory.FRAMEWORK,
    "next.js": SkillCategory.FRAMEWORK,
    "nextjs": SkillCategory.FRAMEWORK,
    "express": SkillCategory.FRAMEWORK,
    "nest.js": SkillCategory.FRAMEWORK,
    "nestjs": SkillCategory.FRAMEWORK,
    "django": SkillCategory.FRAMEWORK,
    "flask": SkillCategory.FRAMEWORK,
    "fastapi": SkillCategory.FRAMEWORK,
    "spring": SkillCategory.FRAMEWORK,
    "spring boot": SkillCategory.FRAMEWORK,
    "laravel": SkillCategory.FRAMEWORK,
    "rails": SkillCategory.FRAMEWORK,
    "ruby on rails": SkillCategory.FRAMEWORK,
    "asp.net": SkillCategory.FRAMEWORK,
    "dotnet": SkillCategory.FRAMEWORK,
    "node.js": SkillCategory.FRAMEWORK,
    "node": SkillCategory.FRAMEWORK,
    "nodejs": SkillCategory.FRAMEWORK,
    "react native": SkillCategory.FRAMEWORK,
    "flutter": SkillCategory.FRAMEWORK,
    "bootstrap": SkillCategory.FRAMEWORK,
    "tailwind": SkillCategory.FRAMEWORK,
    "tailwindcss": SkillCategory.FRAMEWORK,

    # Databases
    "postgresql": SkillCategory.DATABASE,
    "postgres": SkillCategory.DATABASE,
    "mysql": SkillCategory.DATABASE,
    "mongodb": SkillCategory.DATABASE,
    "mongo": SkillCategory.DATABASE,
    "redis": SkillCategory.DATABASE,
    "sqlite": SkillCategory.DATABASE,
    "oracle": SkillCategory.DATABASE,
    "cassandra": SkillCategory.DATABASE,
    "elasticsearch": SkillCategory.DATABASE,
    "dynamodb": SkillCategory.DATABASE,
    "firebase": SkillCategory.DATABASE,
    "firestore": SkillCategory.DATABASE,
    "mariadb": SkillCategory.DATABASE,
    "neo4j": SkillCategory.DATABASE,
    "pinecone": SkillCategory.DATABASE,
    "milvus": SkillCategory.DATABASE,
    "chromadb": SkillCategory.DATABASE,

    # Cloud Platforms
    "aws": SkillCategory.CLOUD,
    "amazon web services": SkillCategory.CLOUD,
    "azure": SkillCategory.CLOUD,
    "gcp": SkillCategory.CLOUD,
    "google cloud": SkillCategory.CLOUD,
    "google cloud platform": SkillCategory.CLOUD,
    "heroku": SkillCategory.CLOUD,
    "digitalocean": SkillCategory.CLOUD,
    "s3": SkillCategory.CLOUD,
    "ec2": SkillCategory.CLOUD,
    "rds": SkillCategory.CLOUD,
    "lambda": SkillCategory.CLOUD,
    "ecs": SkillCategory.CLOUD,
    "eks": SkillCategory.CLOUD,

    # Libraries / Packages
    "pandas": SkillCategory.LIBRARY,
    "numpy": SkillCategory.LIBRARY,
    "scikit-learn": SkillCategory.LIBRARY,
    "sklearn": SkillCategory.LIBRARY,
    "tensorflow": SkillCategory.LIBRARY,
    "pytorch": SkillCategory.LIBRARY,
    "keras": SkillCategory.LIBRARY,
    "spacy": SkillCategory.LIBRARY,
    "nltk": SkillCategory.LIBRARY,
    "opencv": SkillCategory.LIBRARY,
    "scipy": SkillCategory.LIBRARY,
    "matplotlib": SkillCategory.LIBRARY,
    "seaborn": SkillCategory.LIBRARY,
    "huggingface": SkillCategory.LIBRARY,
    "transformers": SkillCategory.LIBRARY,
    "redux": SkillCategory.LIBRARY,
    "graphql": SkillCategory.LIBRARY,
    "langchain": SkillCategory.LIBRARY,
    "llamaindex": SkillCategory.LIBRARY,

    # Tools / Technologies
    "docker": SkillCategory.TOOL,
    "kubernetes": SkillCategory.TOOL,
    "git": SkillCategory.TOOL,
    "github": SkillCategory.TOOL,
    "gitlab": SkillCategory.TOOL,
    "jenkins": SkillCategory.TOOL,
    "ansible": SkillCategory.TOOL,
    "terraform": SkillCategory.TOOL,
    "jira": SkillCategory.TOOL,
    "confluence": SkillCategory.TOOL,
    "postman": SkillCategory.TOOL,
    "webpack": SkillCategory.TOOL,
    "vite": SkillCategory.TOOL,
    "npm": SkillCategory.TOOL,
    "yarn": SkillCategory.TOOL,
    "pnpm": SkillCategory.TOOL,
    "pip": SkillCategory.TOOL,
    "poetry": SkillCategory.TOOL,
    "nginx": SkillCategory.TOOL,
    "apache": SkillCategory.TOOL,
    "github actions": SkillCategory.TOOL,
    "ci/cd": SkillCategory.TOOL,
    "cicd": SkillCategory.TOOL,

    # Concepts / Architecture
    "rest": SkillCategory.OTHER,
    "restful": SkillCategory.OTHER,
    "api": SkillCategory.OTHER,
    "apis": SkillCategory.OTHER,
    "microservices": SkillCategory.OTHER,
    "grpc": SkillCategory.OTHER,
    "jwt": SkillCategory.OTHER,
    "oauth": SkillCategory.OTHER,
    "tdd": SkillCategory.OTHER,
    "bdd": SkillCategory.OTHER,
    "agile": SkillCategory.SOFT_SKILL,
    "scrum": SkillCategory.SOFT_SKILL,
    "kanban": SkillCategory.SOFT_SKILL,

    # Soft Skills
    "leadership": SkillCategory.SOFT_SKILL,
    "communication": SkillCategory.SOFT_SKILL,
    "problem solving": SkillCategory.SOFT_SKILL,
    "teamwork": SkillCategory.SOFT_SKILL,
    "collaboration": SkillCategory.SOFT_SKILL,
    "management": SkillCategory.SOFT_SKILL,
    "critical thinking": SkillCategory.SOFT_SKILL,
    "creativity": SkillCategory.SOFT_SKILL,
    "adaptability": SkillCategory.SOFT_SKILL,
}
